<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payments Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ddd;
        }
        .header h1 {
            margin: 0;
            color: #0d6efd;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #6c757d;
        }
        .filters {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        .filters h3 {
            margin-top: 0;
            font-size: 14px;
        }
        .filters-table {
            width: 100%;
            border-collapse: collapse;
        }
        .filters-table td {
            padding: 4px;
            border: none;
        }
        .filters-table td:first-child {
            font-weight: bold;
            width: 120px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .summary {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
        }
        .summary-container {
            display: flex;
            justify-content: space-between;
        }
        .summary-section {
            width: 48%;
        }
        .summary h3 {
            margin-top: 0;
            font-size: 14px;
        }
        .summary table {
            width: 100%;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #6c757d;
        }
        .status-paid {
            color: #198754;
            font-weight: bold;
        }
        .status-pending, .status-unpaid {
            color: #fd7e14;
            font-weight: bold;
        }
        .status-overdue {
            color: #dc3545;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Spider Web - Payments Report</h1>
        <p>Generated on: {{ $generated_at }}</p>
        <p>Generated by: {{ $generated_by }}</p>
    </div>
    
    <div class="filters">
        <h3>Report Filters</h3>
        <table class="filters-table">
            <tr>
                <td>Date Range:</td>
                <td>{{ $filters['start_date'] }} to {{ $filters['end_date'] }}</td>
                <td>Status:</td>
                <td>{{ ucfirst($filters['status']) }}</td>
            </tr>
            <tr>
                <td>Contract:</td>
                <td>{{ $filters['contract_id'] }}</td>
                <td>Total Records:</td>
                <td>{{ $summary['count'] }}</td>
            </tr>
        </table>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Contract #</th>
                <th>Customer</th>
                <th>Amount (SAR)</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Payment Method</th>
                <th>Reference</th>
                <th>Reconciled</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payments as $payment)
                <tr>
                    <td>{{ $payment->invoice_number }}</td>
                    <td>{{ $payment->contract->contract_number }}</td>
                    <td>{{ $payment->customer->name }}</td>
                    <td>{{ number_format($payment->payment_amount, 2) }}</td>
                    <td>{{ $payment->due_date }}</td>
                    <td class="status-{{ $payment->payment_status }}">
                        {{ ucfirst($payment->payment_status) }}
                    </td>
                    <td>{{ ucfirst(str_replace('_', ' ', $payment->payment_method ?? 'N/A')) }}</td>
                    <td>{{ $payment->payment_reference ?? 'N/A' }}</td>
                    <td>{{ $payment->reconciled ? 'Yes' : 'No' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="summary">
        <div class="summary-container">
            <div class="summary-section">
                <h3>Financial Summary</h3>
                <table>
                    <tr>
                        <td><strong>Total Amount:</strong></td>
                        <td>{{ number_format($summary['total_amount'], 2) }} SAR</td>
                    </tr>
                    <tr>
                        <td><strong>Paid Amount:</strong></td>
                        <td>{{ number_format($summary['paid_amount'], 2) }} SAR</td>
                    </tr>
                    <tr>
                        <td><strong>Pending Amount:</strong></td>
                        <td>{{ number_format($summary['pending_amount'], 2) }} SAR</td>
                    </tr>
                    <tr>
                        <td><strong>Overdue Amount:</strong></td>
                        <td>{{ number_format($summary['overdue_amount'], 2) }} SAR</td>
                    </tr>
                </table>
            </div>
            
            <div class="summary-section">
                <h3>Payment Status Summary</h3>
                <table>
                    <tr>
                        <td><strong>Total Payments:</strong></td>
                        <td>{{ $summary['count'] }}</td>
                    </tr>
                    <tr>
                        <td><strong>Paid Payments:</strong></td>
                        <td>{{ $summary['paid_count'] }}</td>
                    </tr>
                    <tr>
                        <td><strong>Pending Payments:</strong></td>
                        <td>{{ $summary['pending_count'] }}</td>
                    </tr>
                    <tr>
                        <td><strong>Overdue Payments:</strong></td>
                        <td>{{ $summary['overdue_count'] }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    
    <div class="footer">
        <p>This report is generated automatically by the Spider Web system. For any questions, please contact the finance department.</p>
        <p>&copy; {{ date('Y') }} Spider Web. All rights reserved.</p>
    </div>
</body>
</html>
